version: '3'

services:
  # mongodb:
  #   image: mongo
  #   env_file: mongo.env
  #   hostname: wikijs-mongo
  #   networks:
  #     - blog
  #   volumes:
  #     - mongodb

  wikijs-centos7:
    build:
      context: wikijs-centos7
    hostname: wikijs
    networks:
      - blog
    ports:
      - "8080:3000"
    # links:
    #   - mongodb:wikijs-mongo

networks:
  blog:
    driver: bridge

# volumes:
#   mongodb:
